simse/config/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve
from common.views import HomeView, View404, View500, ConfigDjangoJs

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="inicio"),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('config.apis_urls', namespace='api')),
    url(r'^', include('inventario.urls', namespace='inventario_app')),
    url(r'^', include('encargado.urls', namespace='encargados_app')),
    url(r'^', include('reporte.urls', namespace='reporte_app')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('notificaciones.urls', namespace='notificaciones_app')),    
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^(?!api|admin|\.).*$', HomeView.as_view(), name='home'),
    url(r'^config_django.js$', ConfigDjangoJs.as_view(content_type="application/javascript"), name="config_django"),

    
    #url(r'^template/skin-config.html/$', views.skin_config, name='skin_config'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = View404.as_view()
handler500 = View500.as_view()

if settings.DEBUG:

    urlpatterns += [
        url(r'^(?P<path>(favicon.ico))$', serve, {'document_root': settings.STATICFILES_DIRS[0]})
    ]

    import sys
    if "debug_toolbar" in sys.modules:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

simse/encargado/urls.py
from django.conf.urls import include, url
from django.views.decorators.csrf import csrf_exempt
from common.decorators import Token
from .views import *
from .ajax import *

urlpatterns = [
    url(r'^encargados/$', Token(encargados), name="encargados"),
    url(r'^utilidades/$', Token(utilidades), name="utilidades"),
	url(r'^encargado/registrar$', Token(registrar), name="registrar_encargado"),
	url(r'^encargado/listar$', Token(listar), name="listar_encargado"),
	url(r'^encargado/modificar/(?P<pk>[0-9\.]+)$', Token(modificar), name="modificar_encargado"),
	url(r'^encargado/cuentas/(?P<pk>[0-9\.]+)$', Token(cuentas_encargado), name="encargados"),
    url(r'^encargado/ventas$', Token(ventas), name="ventas"),
    url(r'^encargado/ventas/reporte$', Token(encargado_ventas_reporte), name="encargado_ventas_reporte"),
    url(r'^encargado/ventas/reporte_metodo$', Token(encargado_metodo_reporte), name="encargado_metodo_reporte"),
    url(r'^encargado/ventas/listar$', Token(listar_ventas), name="listar_ventas"),
    url(r'^encargado/ventas/listar/(?P<pk>[0-9\.]+)$', Token(listar_ventas_encargado), name="listar_ventas_encargado"),
    url(r'^encargado/ventas/listar_cliente/(?P<pk>[0-9\.]+)$', Token(listar_ventas_cliente), name="listar_ventas_cliente"),
    url(r'^encargado/ventas/listar_cliente/iframe/(?P<pk>[0-9\.]+)$',
        Token(listar_ventas_cliente_iframe),
        name="listar_ventas_cliente_iframe"),
    url(r'^encargado/ventas/pagos$', Token(pagos), name="pagos"),
    url(r'^encargado/ventas/pagos/(?P<pk>[0-9\.]+)$', Token(pagos_venta), name="pagos"),
    url(r'^encargado/clientes/listar$', Token(listar_clientes), name="listar_clientes"),
    url(r'^encargado/clientes/listar/(?P<pk>[0-9\.]+)$', Token(listar_clientes_encargado), name="listar_clientes_encargado"),


    url(r'^inventario/encargado/listar$', Token(listar_inventario), name="listar_inventario_encargado"),


	url(r'^ajax/listar_encargado$', csrf_exempt(ListarEncargado.as_view()) , name="listar_encargado_ajax"),
	url(r'^ajax/listar_inventario_encargado$', csrf_exempt(ListarStockEncargado.as_view()), name="listar_inventario_encargado_ajax"),
    url(r'^ajax/listar_transacciones$', csrf_exempt(ListarTransacciones.as_view()), name="listar_transacciones_ajax"),
    url(r'^ajax/listar_transacciones_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarTransaccionesEncargado.as_view()), name="listar_transacciones_encargado_ajax"),
    
    url(r'^ajax/listar_ventas_reporte$', csrf_exempt(ListarVentasReporte.as_view()),
        name="listar_ventas_reporte_ajax"),
    url(r'^ajax/listar_ventas_reporte_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarVentasReporteEncargado.as_view()),
        name="listar_ventas_reporte_encargado_ajax"),
    
    url(r'^ajax/listar_ventas$', csrf_exempt(ListarVentas.as_view()), name="listar_ventas_ajax"),
    url(r'^ajax/listar_ventas_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarVentasEncargado.as_view()),
    	name="listar_ventas_encargado_ajax"),

    url(r'^ajax/listar_clientes$', csrf_exempt(ListarClientes.as_view()), name="listar_clientes_ajax"),
    url(r'^ajax/listar_clientes_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarClientesEncargado.as_view()),
        name="listar_clientes_encargado_ajax"),

    url(r'^ajax/listar_ventas_cliente/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarVentasCliente.as_view()),
        name="listar_ventas_cliente_ajax"),

    url(r'^ajax/listar_pagos_venta$', csrf_exempt(ListarPagos.as_view()), name="listar_pagos_ajax"),
    url(r'^ajax/listar_pagos_venta/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarPagosVenta.as_view()),
        name="listar_pagos_venta_ajax"),

    url(r'^ajax/listar_ventas_reporte_metodo/$', csrf_exempt(ListarVentasReporteMetodo.as_view()),
        name="listar_ventas_reporte_metodo_ajax"),
    url(r'^ajax/listar_ventas_reporte_encargado_metodo/(?P<pk>[0-9\.]+)/$',
        csrf_exempt(ListarVentasReporteMetodoEncargado.as_view()),
        name="listar_ventas_reporte_metodo_encargado_ajax"),
    

]

simse/reporte/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from rest_framework.routers import SimpleRouter
from .viewsets import ReporteLocalEncargadoViewSet,\
  ReporteLocalViewSet, ReporteCierreViewSet, CierreViewSet

router = SimpleRouter()
router.register("cierre", CierreViewSet)

urlpatterns = [
	
	url(r'^reporte/local/encargado/(?P<pk>\d+)$', ReporteLocalEncargadoViewSet.as_view(),
		name="reporte-local-encargado"),
	url(r'^reporte/local/$', ReporteLocalViewSet.as_view(),
		name="reporte-local-encargado"),	

    url(r'^reporte/cierre/$', ReporteCierreViewSet.as_view(),
        name="reporte-cierre"),   

    url(r'^', include(router.urls)),             
]

simse/reporte/urls.py
from django.conf.urls import include, url
from django.views.decorators.csrf import csrf_exempt

from common.decorators import Token

from .views import *
from .ajax import *

urlpatterns = [
    url(r'^offline.appcache$', app_cache, name="app_cache"),  
    url(r'^reporte/listar$', Token(lista_reportes), name="lista_reportes"),
    url(r'^reporte/cierre$', Token(cierre), name="cierre"),
    url(r'^reporte/administrador_ventas$', administrador_ventas, name="administrador_ventas"),
    url(r'^reporte/ventas_detallado$', ventas_detallado, name="ventas_detallado"),
    
    url(r'^reporte/detalle/cierre/(?P<pk>[0-9\.]+)/$', detalle_cierre, name="detalle_cierre"),
    url(r'^reporte/detalle/cierre_cliente/(?P<pk>[0-9\.]+)/$', cierre_cliente, name="cierre_cliente"),

    url(r'^ajax/listar_reporte_local$', csrf_exempt(ListarReporteLocal.as_view()), name="listar_reporte_local_ajax"),
    url(r'^ajax/listar_reporte_local_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarReporteLocalEncargado.as_view()),
    	name="listar_reporte_local_encargado_ajax"),

    url(r'^ajax/listar_reporte_cierre$', csrf_exempt(ListarCierres.as_view()),
        name="listar_reporte_cierre_ajax"),

    url(r'^ajax/listar_reporte_cierre_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarCierresEncargado.as_view()),
        name="listar_reporte_cierre_encargado_ajax"),
    url(r'^ajax/detalle_reporte_cierre_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarCierreDetalle.as_view()),
        name="detalle_reporte_cierre_encargado_ajax"),

    url(r'^ajax/dcc/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarCierreClienteDetalle.as_view()),
        name="detalle_reporte_cierre_cliente_ajax"),



    url(r'^ajax/listar_reporte_venta_detalle$', csrf_exempt(ListarReporteVentaDetalle.as_view()),
        name="listar_reporte_venta_detalle_ajax"),


]

simse/reporte/models.py
from django.db import models
from common.models import UserOneBaseModel, BaseModel, UserRelationBaseModel, Permiso
from django.utils.translation import ugettext_lazy as _
from accounts.models import Persona

class Inversionista(UserOneBaseModel):
    
    permisos = models.ManyToManyField(Permiso, blank=True)
    persona = models.OneToOneField(Persona)

    def __str__(self):
        return str(self.persona)

simse/reporte/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse

from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required


def app_cache(request):
    c=open('offline.txt','r')
    return HttpResponse(c.read(), content_type='text/cache-manifest')


def dias_trabajo_empleados(request):
    return render(request, 'dias_trabajo_empleados.html', {})


def reporte_encargado(request, pk):
    context = {
        'temporada': pk
    }
    return render(request,'reporte_encargado.html',context)


def administrador_ventas(request):
    return render(request, 'administrador_ventas_reporte.html', {})

def ventas_detallado(request):
    return render(request, 'listar_ventas_cliente_detallado.html', {})


def cierre(request):
    return render(request,'listar_cierre.html',{}) 

def lista_reportes(request):
    return render(request,'lista_reportes.html',{}) 

def detalle_cierre(request,pk):
    return render(request,'detalle_cierre.html',{'pk':pk}) 


def cierre_cliente(request,pk):
    return render(request,'detalle_cierre_cliente.html',{'pk':pk}) 

simse/reporte/templates/detalle_cierre_cliente.html
{% extends "base_simple.html" %}
{% load static %}
{% block titulo %} Detalle cierre cliente{% endblock titulo %}
 
{% block pagina %}
<div class="row">
    <div class="col-md-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Detalle del Cierre</h5>
        </div>
        <div class="ibox-content">
            <table class="table table-bordered table-hover dataTables-example" >
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>telefono</th>
                        <th>venta</th>
                        <th>Deuda</th>
                    </tr>
                </thead>
                <tbody>
                    <tr></tr>
                </tbody>
            </table>
          
        </div>
      </div> <!-- cols 12 -->
    </div>
</div>

{% endblock pagina %}


{% block extra_js %}
<script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/dataTables/datatables.min.js' %}"></script>
<script src="{% static 'js/dataTables/colvis.js' %}"></script>
<script src="{% static 'js/sertiven/red.js' %}"></script>
<script type="text/javascript">
get_usuario_conectado();
HDD.set('last_url',window.location.pathname);
$('#menu_reporte').addClass('active');
var oTable;
var url = "{% url 'reporte_app:detalle_reporte_cierre_cliente_ajax' pk %}"

$(document).ready(function () {

    oTable = $('.table').dataTable({
    "aaSorting":[[0,"desc"]],
    "language": {
    "sLengthMenu":     "Mostrar _MENU_ cliente",
    "sZeroRecords":    "No se encontraron resultados",
    "sEmptyTable":     "Ningún dato disponible en esta tabla",
    "sInfo":           "Mostrando cliente del _START_ al _END_ de un total de _TOTAL_ cliente",
    "sInfoEmpty":      "Mostrando cliente del 0 al 0 de un total de 0 cliente",
    "sInfoFiltered":   "(filtrado de un total de _MAX_ cliente)",
    "sInfoPostFix":    "",
    "sSearch":         "Buscar:",
    "sUrl":            "",
    "sInfoThousands":  ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
      "sFirst":    "Primero",
      "sLast":     "Último",
      "sNext":     "Siguiente",
      "sPrevious": "Anterior"
    },
    "oAria": {
      "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
      "sSortDescending": ": Activar para ordenar la columna de manera descendente"
      }
    },
    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
    "processing": true,
    "serverSide": true,
    "ajax": {
        "url": url,
        "type": "POST", 
        "headers": { 'Authorization':  HDD.get(settings.jwt_name) },
    }
  }); 
});
</script>
{% endblock extra_js %}

simse/reporte/templates/lista_reportes.html
{% extends "base_ajax.html" %}
{% load static %}
{% block titulo %}Lista de reportes{% endblock titulo %}

{% block pagina %}
<div class="row">

<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <a href="#{% url 'encargados_app:listar_ventas' %}">
      <div class="widget style1 navy-bg">
          <div class="row">
            <div class="col-xs-5 text-letf">
                <span> Reporte de ventas de encargados </span>
            </div>
            <div class="col-xs-3">
                <i class="fa fa-check-double fa-3x"></i>
            </div>
            <div class="col-xs-4 text-right">
              <h2 class="font-bold" ></h2>
            </div>
          </div>
      </div>    
    </a>
  </div>

  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <a href="#{% url 'reporte_app:administrador_ventas' %}">
      <div class="widget style1 navy-bg">
          <div class="row">
            <div class="col-xs-5 text-letf">
                <span> Reporte de Encargados</span>
            </div>
            <div class="col-xs-3">
                <i class="fa fa-check-double fa-3x"></i>
            </div>
            <div class="col-xs-4 text-right">
              <h2 class="font-bold" ></h2>
            </div>
          </div>
      </div>    
    </a>
  </div>

  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <a href="#{% url 'reporte_app:cierre' %}">
      <div class="widget style1 navy-bg">
          <div class="row">
            <div class="col-xs-5 text-letf">
                <span> Cierre de Encargados</span>
            </div>
            <div class="col-xs-3">
                <i class="fa fa-check-double fa-3x"></i>
            </div>
            <div class="col-xs-4 text-right">
              <h2 class="font-bold" ></h2>
            </div>
          </div>
      </div>    
    </a>
  </div>
</div>


<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <a href="#{% url 'reporte_app:ventas_detallado' %}">
      <div class="widget style1 navy-bg">
          <div class="row">
            <div class="col-xs-5 text-letf">
                <span> Reporte ventas cliente detallado </span>
            </div>
            <div class="col-xs-3">
                <i class="fa fa-check-double fa-3x"></i>
            </div>
            <div class="col-xs-4 text-right">
              <h2 class="font-bold" ></h2>
            </div>
          </div>
      </div>    
    </a>
  </div>

  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <a href="#{% url 'encargados_app:encargado_metodo_reporte' %}">
      <div class="widget style1 navy-bg">
          <div class="row">
            <div class="col-xs-5 text-letf">
                <span> Reporte ventas metodos de pagos</span>
            </div>
            <div class="col-xs-3">
                <i class="fa fa-check-double fa-3x"></i>
            </div>
            <div class="col-xs-4 text-right">
              <h2 class="font-bold" ></h2>
            </div>
          </div>
      </div>    
    </a>
  </div>


</div>




</div>
{% endblock pagina %}
{% block extra_js %}

<!-- Flot -->
<script src="{% static 'js/flot/jquery.flot.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.spline.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.symbol.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.time.js' %}"></script>
<!-- Flot -->

<!-- Jvectormap -->
<script src="{% static 'js/jvectormap/jquery-jvectormap-2.0.2.min.js' %}"></script>
<script src="{% static 'js/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- Jvectormap -->


<script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/easypiechart/jquery.easypiechart.js' %}"></script>
<script src="{% static 'js/chartJs/Chart.min.js' %}"></script>
<!-- 
<script src="{% static 'js/chartJs/chartjs-demo.js' %}"></script>
 -->
<script type="text/javascript">
$('#menu_reporte').addClass('active');
get_usuario_conectado();
HDD.set('last_url',window.location.pathname);
</script>
{% endblock extra_js %}

simse/reporte/templates/listar_cierre.html
{% extends "base_ajax.html" %}
{% load static %}
{% block titulo %} Lista de Cierres {% endblock titulo %}

{% block pagina %}
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
          <h5>Lista de cierres</h5>
      </div>
      <div class="ibox-content">
        {% if not request.user.is_superuser %}
        <div class="row">
              <div class="col-lg-4 col-md-4 col-xs-6">
                  <div class="widget style1 navy-bg">
                      <div class="row">
                        <div class="col-xs-3 text-letf">
                            <span>Fecha Cierre</span>
                        </div>
                        <div class="col-xs-9">
                          <div class="form-group" id="data_4">
                              <div class="input-group date">
                                  <span class="input-group-addon"><i class="fa fa-calendar-minus"></i></span>
                                  <input class="form-control" data-date-format="dd-mm-yyyy" id="fecha_fin" type="text" autocomplete="on" placeholder="dd-mm-aaaa"></input>
                              </div>
                          </div>
                        </div>
                      </div>
                  </div>
              </div>
              <div class="col-lg-2 col-md-2 col-xs-4">
                <div class="widget style2 lazur-bg">
                  <div class="row">
                    <div class="col-xs-12 text-letf">
                        <button class="btn btn-success" onclick="nuevo_cierre()">Cierre</button>
                    </div>
                  </div>
                </div>
              </div>

          <div class="col-sm-3 col-md-offset-9">
          </div>
        </div>
        {% endif %}
        <table class="table table-bordered table-hover dataTables-example" >
        <thead>
        <tr>
            <th>Fecha Inicio</th>
            <th>Fecha Fin</th>
            <th>Encargado</th>
            <th>Ganancia</th>
            <th>Diferencia</th>
            <th>Total Neto</th>
            <th>Botones</th>
        </tr>
        </thead>
          <tbody>
              <tr></tr>
          </tbody>
        </table>
      </div>
      </div>
  </div> <!-- cols 12 -->
</div>
{% endblock pagina %}


{% block extra_js %}
<script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/dataTables/datatables.min.js' %}"></script>
<script src="{% static 'js/dataTables/colvis.js' %}"></script>
<script src="{% static 'js/datapicker/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/datapicker/bootstrap-datepicker.es.js' %}"></script>
<script type="text/javascript">
$('#menu_encargado').addClass('active');
get_usuario_conectado();

function nuevo_cierre() {

    swal({
        title: "Crear el cierre",
        text: '¿Deseas crear el cierre',
        type: "success",
        showCancelButton: true,
        confirmButtonColor: "blue",
        confirmButtonText: "Crear",
        closeOnConfirm: false,
        html: true
    }, function () {
      url = '/api/v1/reporte/cierre/'
      $.ajax({
        type: "POST",
        url:   url,
        data: {
          fecha_fin_cierre: $("#fecha_fin").val()
        },
        beforeSend: function (xhr) {
          xhr.setRequestHeader("Authorization", 'JWT '+ HDD.get(settings.jwt_name));
        },
        complete: function (Req, textStatus, jqXHR)
        {
          respuesta = Req.responseJSON;
          if (Req.status === 201) 
          {
            _exito_reload('Se creo el cierre')            
          }
          else
          {
            _error(respuesta.errors['mensaje'])
          }

        }// fin complete
      })        
  });


}

function eliminar_dato(id) {
    swal({
        title: "Eliminar el cierre",
        text: '¿Deseas eliminar el cierre seleccionado?',
        type: "success",
        showCancelButton: true,
        confirmButtonColor: "red",
        confirmButtonText: "Eliminar",
        closeOnConfirm: false,
        html: true
    }, function () {

      $.ajax({
        type: "DELETE", //GET, POST, PUT, PATCH 
        url:   '/api/v1/cierre/' + id + '/?borrar=true', 
        beforeSend: function (xhr) {   //Include the bearer token in header
          xhr.setRequestHeader("Authorization", 'JWT '+ HDD.get(settings.jwt_name));
        },
        complete: function (Req, textStatus)
        {
          if (Req.status === 204) 
          {
            swal({  
              title: "",
              text: "Se ha eliminado exitosamente.",
              type: "success",
              showCancelButton: false,
              confirmButtonColor: "#23c6c8",
              confirmButtonText: "Cerrar",
              closeOnConfirm: false
              }, function () {
                location.reload();
            });
          }               
        }// fin complete
      })

  });

}

$(document).ready(function () {


  $('.input-group.date').datepicker({
      language: 'es',
      startView: 4,
      todayBtn: "linked",
      todayHighlight: 1,
      keyboardNavigation: false,
      forceParse: false,
      autoclose: true,
      format: 'dd-mm-yyyy'
  });
  

    if (HDD.get('administrador') == 'si')
    {
        var url = "{% url 'reporte_app:listar_reporte_cierre_ajax' %}"
    }
    else
    {
        var url = "{% url 'reporte_app:listar_reporte_cierre_encargado_ajax' 0 %}".replace(0,
        HDD.get('encargado_id'))
    }


    var oTable = $('.table').dataTable({
        "aaSorting":[[0,"desc"]],
        "language": {
        "sLengthMenu":     "Mostrar _MENU_ cierres",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando cierres del _START_ al _END_ de un total de _TOTAL_ cierres",
        "sInfoEmpty":      "Mostrando cierres del 0 al 0 de un total de 0 cierres",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ cierres)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
          "sFirst":    "Primero",
          "sLast":     "Último",
          "sNext":     "Siguiente",
          "sPrevious": "Anterior"
        },

        "oAria": {
          "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      },
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": url,
            "type": "POST",
            "headers": { 'Authorization':  HDD.get(settings.jwt_name) },
        }
    });
});
</script>
{% endblock extra_js %}