simse/config/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve
from common.views import HomeView, View404, View500, ConfigDjangoJs

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="inicio"),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('config.apis_urls', namespace='api')),
    url(r'^', include('inventario.urls', namespace='inventario_app')),
    url(r'^', include('encargado.urls', namespace='encargados_app')),
    url(r'^', include('reporte.urls', namespace='reporte_app')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('notificaciones.urls', namespace='notificaciones_app')),    
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^(?!api|admin|\.).*$', HomeView.as_view(), name='home'),
    url(r'^config_django.js$', ConfigDjangoJs.as_view(content_type="application/javascript"), name="config_django"),

    
    #url(r'^template/skin-config.html/$', views.skin_config, name='skin_config'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = View404.as_view()
handler500 = View500.as_view()

if settings.DEBUG:

    urlpatterns += [
        url(r'^(?P<path>(favicon.ico))$', serve, {'document_root': settings.STATICFILES_DIRS[0]})
    ]

    import sys
    if "debug_toolbar" in sys.modules:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

simse/inventario/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from rest_framework.routers import SimpleRouter
from .viewsets import StockViewSet, StockDetailViewSet,\
StockChangeViewSet, ProductoViewSet, StockEncargadoViewSet, \
StockMontoViewSet, AsignacionStockAceptarViewSet, AsignacionStockAsignarViewSet,\
StockProductoViewSet, StockEncargadoDetailViewSet, EncargadoAEncargadoViewSet,\
AsignacionStockAceptarProductosViewSet, StockProductoEncargadoDetailViewSet,\
EliminarStockProductosEncargados, ProductoListViewSet, PrecioDolarViewSet


router = SimpleRouter()
router.register("list_producto", ProductoListViewSet)
router.register("producto", ProductoViewSet)


urlpatterns = [

	url(r'^stock/(?P<pk>\d+)/change/$', StockChangeViewSet.as_view(), name="stock-change"), 
    url(r'^stock/producto/(?P<pk>\d+)/monto/$', StockMontoViewSet.as_view(), name="stock-monto"),
    url(r'^stock/(?P<pk>\d+)/aceptar/$', AsignacionStockAceptarViewSet.as_view(),
        name="stock-aceptar"),
    url(r'^stock/(?P<pk>\d+)/aceptar_por_productos/$', AsignacionStockAceptarProductosViewSet.as_view(),
        name="stock-aceptar-por-productos"),    
    url(r'^stock/(?P<pk>\d+)/$', StockDetailViewSet.as_view(), name="stock-detail"),


    ### aqui puedo asignar teniendo el id del stock
    url(r'^stock/(?P<pk>\d+)/asignar/$', AsignacionStockAsignarViewSet.as_view(),
        name="stock-asignar"),    

    ### aqui puedo asignar sin tener el id del stock
    url(r'^stock/encargado/$', StockEncargadoViewSet.as_view(), name="stock-encargado"),
    
    url(r'^stock/encargado/(?P<pk>\d+)/$', StockEncargadoDetailViewSet.as_view(),
        name="stock-encargado-detail"),    
    url(r'^stock_para_producto/encargado/(?P<pk>\d+)/$', StockProductoEncargadoDetailViewSet.as_view(),
        name="stock-encargado-detail"), 


    url(r'^stock_para_producto/(?P<pk>\d+)/encargado_a_encargado/$', EncargadoAEncargadoViewSet.as_view(),
        name="encargado-a-encargado"),

    url(r'^stock_para_producto/(?P<p>\d+)/(?P<e>\d+)/$', EliminarStockProductosEncargados.as_view(),
        name="eliminar-stock-producto-encargado"),

    url(r'^stock/producto/(?P<pk>\d+)/$', StockProductoViewSet.as_view(), name="stock-producto"),
    url(r'^stock/precio_dolar/(?P<pk>\d+)/$', PrecioDolarViewSet.as_view(), name="stock-precio_dolar"),
    url(r'^stock/$', StockViewSet.as_view(), name="stock"),
    url(r'^', include(router.urls)), 

]

simse/inventario/urls.py
from django.conf.urls import include, url
from django.views.decorators.csrf import csrf_exempt
from common.decorators import Token
from .views import *
from .ajax import ListarStock, ListarStockProducto, ListarProductos,\
    ListarStockEncargado, ListarTraslados, ListarStockEncargadoAceptarNuevo,\
    ListarTrasladosSucursales

urlpatterns = [
	url(r'^inventario/registrar$', Token(registrar), name="registrar_inventario"),
	url(r'^inventario/listar$', Token(listar_inventario), name="listar_inventario"),
    url(r'^inventario/detalle/producto/(?P<pk>[0-9\.]+)/$', Token(detalle), name="registrar_inventario"),

	url(r'^ajax/listar_inventario$', csrf_exempt(ListarStock.as_view()), name="listar_inventario_ajax"),
    url(r'^ajax/listar_inventario_encargado$', csrf_exempt(ListarStockEncargado.as_view()),
        name="listar_inventario_encargado_ajax"),
    url(r'^ajax/listar_inventario_encargado_aceptar$', csrf_exempt(ListarStockEncargadoAceptarNuevo.as_view()),
        name="listar_inventario_encargado_aceptar_ajax"),

    url(r'^ajax/listar_traslados_sucursales$', csrf_exempt(ListarTrasladosSucursales.as_view()),
        name="listar_traslados_sucursales_ajax"),

    url(r'^ajax/listar_productos$', csrf_exempt(ListarProductos.as_view()), name="listar_productos_ajax"),
    url(r'^ajax/listar_traslados$', csrf_exempt(ListarTraslados.as_view()), name="listar_traslados_ajax"),    
    url(r'^ajax/listar_inventario/producto/(?P<pk>[0-9\.]+)/$',
        csrf_exempt(ListarStockProducto.as_view()) , name="listar_inventario_producto_ajax"),

]

simse/reporte/urls.py
from django.conf.urls import include, url
from django.views.decorators.csrf import csrf_exempt

from common.decorators import Token

from .views import *
from .ajax import *

urlpatterns = [
    url(r'^offline.appcache$', app_cache, name="app_cache"),  
    url(r'^reporte/listar$', Token(lista_reportes), name="lista_reportes"),
    url(r'^reporte/cierre$', Token(cierre), name="cierre"),
    url(r'^reporte/administrador_ventas$', administrador_ventas, name="administrador_ventas"),
    url(r'^reporte/ventas_detallado$', ventas_detallado, name="ventas_detallado"),
    
    url(r'^reporte/detalle/cierre/(?P<pk>[0-9\.]+)/$', detalle_cierre, name="detalle_cierre"),
    url(r'^reporte/detalle/cierre_cliente/(?P<pk>[0-9\.]+)/$', cierre_cliente, name="cierre_cliente"),

    url(r'^ajax/listar_reporte_local$', csrf_exempt(ListarReporteLocal.as_view()), name="listar_reporte_local_ajax"),
    url(r'^ajax/listar_reporte_local_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarReporteLocalEncargado.as_view()),
    	name="listar_reporte_local_encargado_ajax"),

    url(r'^ajax/listar_reporte_cierre$', csrf_exempt(ListarCierres.as_view()),
        name="listar_reporte_cierre_ajax"),

    url(r'^ajax/listar_reporte_cierre_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarCierresEncargado.as_view()),
        name="listar_reporte_cierre_encargado_ajax"),
    url(r'^ajax/detalle_reporte_cierre_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarCierreDetalle.as_view()),
        name="detalle_reporte_cierre_encargado_ajax"),

    url(r'^ajax/dcc/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarCierreClienteDetalle.as_view()),
        name="detalle_reporte_cierre_cliente_ajax"),



    url(r'^ajax/listar_reporte_venta_detalle$', csrf_exempt(ListarReporteVentaDetalle.as_view()),
        name="listar_reporte_venta_detalle_ajax"),


]

simse/inventario/models.py
from decimal import Decimal
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.conf import settings
from django.utils import timezone
from common.mensajes import M
from common.models import UserOneBaseModel, BaseModel, UserRelationBaseModel, BaseManager
from accounts.models import Persona
from common.mensajes import M

class Producto(BaseModel):

    nombre = models.CharField(max_length=300)
    unidad = models.CharField(max_length=40, default='lt')

    @property
    def nombre_unidad(self):
        return "%s %s" % (self.nombre, self.unidad)

    @property
    def mi_costo_actual(self):
        try:
            cp = CostoProducto.objects.activos(producto=self).last()
            return cp.monto.monto
        except Exception as e:
            return 0


    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ("nombre",)


class Costo(BaseModel):

    monto = models.DecimalField(max_digits=30, decimal_places=2)

    @staticmethod
    def adquirir(monto):
        try:
            v,c = Costo.objects.get_or_create(monto=monto)
            return v
        except Costo.MultipleObjectsReturned as e:
            return Costo.objects.filter(monto=monto).first()
        

    def __str__(self):
        return str(self.monto)

    class Meta:
        ordering = ("monto",)
        verbose_name = _('Costo')
        verbose_name_plural = _('Costos')


class Stock(UserRelationBaseModel):

    producto = models.ForeignKey(Producto)
    cantidad_recibida = models.DecimalField(max_digits=30, decimal_places=2, default=0)
    cantidad_actual = models.DecimalField(max_digits=30, decimal_places=2, default=0)
    monto = models.ForeignKey(Costo)
    fecha_registro = models.DateField()

    @property
    def costo(self):

        if self.cantidad_recibida != 0:
            return self.monto.monto / self.cantidad_recibida
        return 0

    def get_costo_gastado(self):
        cantida_gastada = self.cantidad_recibida - self.cantidad_actual
        return cantida_gastada * self.costo

    def descontar(self, cant):
        if self.descontable(cant):
            self.cantidad_actual -= cant
            self.save()
            return True
        return False

    def descontable(self, cant):
        if cant <= self.cantidad_actual:
            return True
        return False

    def save(self, *args, **kwargs):
        try:
            monto, creado = Costo.objects.get_or_create(monto=self.monto_tmp)
            self.monto = monto 
        except:
            pass
        super(Stock, self).save(*args, **kwargs)


    class Meta:
        ordering = ("fecha_registro", "producto")
        verbose_name = _('Stock')
        verbose_name_plural = _('Stock')

    def __str__(self):
        return str(self.producto)


class AsignacionStockQuerySet(models.QuerySet):

    def monto_por_vender(self):
        qs = self.filter()
        cant = 0
        for i in qs:
            cant += i.pendiente_por_vender
        return cant


class AsignacionStockManager(BaseManager):

    use_in_migrations = True 

    def get_queryset(self):
        return AsignacionStockQuerySet(self.model, using=self._db)

    def monto_por_vender(self):
        return self.get_queryset().monto_por_vender()


class AsignacionStock(UserRelationBaseModel):

    stock = models.ForeignKey(Stock)
    encargado = models.ForeignKey("encargado.Encargado", related_name='stock')
    cantidad_recibida = models.DecimalField(max_digits=30, decimal_places=2,
                                            default=0)
    cantidad_actual = models.DecimalField(max_digits=30, decimal_places=2,
                                          default=0)
    aceptado = models.BooleanField(default=False)
    fecha_aceptado = models.DateTimeField(null=True, blank=True)
    objects = AsignacionStockManager()

    def __str__(self):
        return str(self.encargado)

    @property
    def pendiente_por_vender(self):
        r = self.cantidad_actual * self.stock.producto.mi_costo_actual
        return r

    def aceptar(self):
        self.aceptado = True
        self.fecha_aceptado = timezone.now()
        self.save()

    def asignar(self):
        self.cantidad_actual = self.cantidad_recibida
        return self.stock.descontar(self.cantidad_recibida)

    def descontar(self, cantidad):
        self.cantidad_actual -= Decimal(cantidad)
        self.save()

    def reversar(self, cantidad):
        self.cantidad_actual += cantidad
        self.save()

    def reenvio_admin(self):
        self.stock.cantidad_actual += self.cantidad_recibida
        self.stock.save()
        self.delete()

    def delete(self, *args, **kwargs):
        super(AsignacionStock, self).delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        if not self.id and not self.asignar():
            raise ValidationError('Cantidad de inventario superada')

        if self.cantidad_actual < 0:
            raise ValidationError(_("Cantidad en stock superada."))
        super(AsignacionStock, self).save(*args, **kwargs)

    def save_no_validate(self, *args, **kwargs):
        super(AsignacionStock, self).save(*args, **kwargs)

    class Meta:
        ordering = ("created",)
        verbose_name = _('Asignacion Stock')
        verbose_name_plural = _('Asignacion Stock')


class TrasladoEncargado(UserRelationBaseModel):

    origen =   models.ForeignKey(AsignacionStock, related_name="origen_set")
    traslado = models.ForeignKey(AsignacionStock, related_name="destino_set")

    class Meta:
        ordering = ("created",)
        verbose_name = _('Traslado Encargado')
        verbose_name_plural = _('Traslados Encargado')


class CostoProducto(BaseModel):

    producto = models.ForeignKey(Producto)
    monto = models.ForeignKey(Costo)
    monto_dolar = models.ForeignKey(Costo, null=True, blank=True, related_name="costoproductomontodolar_set")

    def save(self, *args, **kwargs):
        try:
            monto, creado = Costo.objects.get_or_create(monto=self.monto_tmp)
            self.monto = monto 
        except:
            pass
        super(CostoProducto, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.producto) + ' ' + str(self.monto)

    class Meta:
        ordering = ("id",)
        verbose_name = _('Costo producto')
        verbose_name_plural = _('Costos producto')
        get_latest_by = 'id'



class PrecioDolar(BaseModel):

    monto = models.ForeignKey(Costo)

    def __str__(self):
        return str(self.monto)

    class Meta:
        ordering = ("id",)
        verbose_name = _('Dolar')
        verbose_name_plural = _('Dolares')
        get_latest_by = 'id'

simse/inventario/views.py
from django.shortcuts import render
from .models import Producto
from encargado.models import Encargado 

def listar_inventario(request):
    return render(request,'listar_inventario.html',{})

def registrar(request):
    return render(request,'registrar_inventario.html',{})

def detalle(request, pk):
    producto = Producto.objects.get(pk=pk)
    context = {
        'producto':producto.nombre,
        'id':producto.id
    }
    return render(request,'listar_inventario_producto.html',context)

simse/inventario/templates/cierre_inventario.html
{% extends "base_ajax.html" %}
{% load static %}
{% block titulo %} 

{% if perms.inventario.add %}
Cierre de inventario. 
{% else %}
Cierre de tú inventario. 
{% endif %}

{% endblock titulo %}

{% block head_css %}
    <link href="{% static 'css/sweetalert/sweetalert.css' %}" rel="stylesheet">
    <link href="{% static 'css/dataTables/datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/touchspin/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet">
{% endblock %}


{% block head_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
{% endblock head_js %}

{% block breadcrumb %}
{% endblock %}

{% block pagina %}
  <div class="row">
      <div class="col-md-12">
      <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Cierre de Inventario</h5>
            </div>
            <div class="ibox-content">
                <div class="panel-body">
                    {% if not request.user.is_superuser %}
                    <div class="col-sm-3 col-md-offset-9">
                        <a class="btn btn-sm btn-white btn-block" onclick="nuevo_cierre()"> <i class="fa fa-user-plus" aria-hidden="true"> Nuevo Cierre</i></a>
                    </div>  
                    {% endif %}
                    <table id="cierre" class="table table-bordered table-hover dataTables-example" width="100%">
                    <thead>
                    <tr>
                        <th>Encargado</th>
                        <th>Fecha Inicio</th>
                        <th>Fecha Fin</th>
                        <th>Ganancia</th>
                        <th>Diferencia</th>
                        <th>Total</th>
                        <th>Boton</th>
                    </tr>
                    </thead>
                        <tbody>
                            <tr></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div> <!-- cols 12 -->
</div>


<div class="modal fade bs-example-modal-lg" id="modal_generico" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myLargeModalLabel">

    <div class="modal-dialog modal-lg" role="document">

        <div id="body_modal">
        <div id="loading" width="100%" style="width: 550px;" class="modal-body">
           <img src="{% static "img/loading4.gif" %}"> 
        </div>  
        </div>
    </div>
</div>

{% endblock pagina %}
{% block extra_js %}
<script src="{% static 'js/dataTables/datatables.min.js' %}"></script>
<script src="{% static 'js/touchspin/jquery.bootstrap-touchspin.min.js' %}"></script>
<script type="text/javascript">
get_usuario_conectado();

var lista_cierre = new Array();
var lista_cierre_original = new Array();
var contador_cierre = -1;
var contador_cierre_anteriores = -1;
var total_deducciones_cierre = 0;

utiles.log(settings.debug);


var oTable3;
var oTable4;


$(document).ready(function () {

    $('#menu_cierre').addClass('active');
    refrescar_token();


    oTable3 = $('#cierre').dataTable({
        "aaSorting":[[0,"desc"]],
        "language": {
        "sLengthMenu":     "Mostrar _MENU_ inventarios",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando inventarios del _START_ al _END_ de un total de _TOTAL_ inventarios",
        "sInfoEmpty":      "Mostrando inventarios del 0 al 0 de un total de 0 inventarios",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ inventarios)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
          "sFirst":    "Primero",
          "sLast":     "Último",
          "sNext":     "Siguiente",
          "sPrevious": "Anterior"
        },

        "oAria": {
          "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      },
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "{% url 'reporte_app:listar_reporte_cierre_ajax' %}",
            "type": "POST",
            "headers": { 'Authorization':  HDD.get(settings.jwt_name) },
        }
    });
    
    oTable4 = $('#mis_cierre').dataTable({
        "aaSorting":[[0,"desc"]],
        "language": {
        "sLengthMenu":     "Mostrar _MENU_ inventarios",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando inventarios del _START_ al _END_ de un total de _TOTAL_ inventarios",
        "sInfoEmpty":      "Mostrando inventarios del 0 al 0 de un total de 0 inventarios",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ inventarios)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
          "sFirst":    "Primero",
          "sLast":     "Último",
          "sNext":     "Siguiente",
          "sPrevious": "Anterior"
        },

        "oAria": {
          "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      },
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "{% url 'inventario_app:listar_inventario_encargado_aceptar_ajax' %}",
            "type": "POST",
            "headers": { 'Authorization':  HDD.get(settings.jwt_name) },
        }
    });
});// fin ready

</script>
{% endblock extra_js %}

simse/inventario/templates/listar_inventario_producto.html
{% extends "base_ajax.html" %}
{% load static %}
{% block titulo %} Lista de Inventarios {% endblock titulo %}

 

{% block breadcrumb %}
{% endblock %}

{% block pagina %}
  <div class="row">
      <div class="col-md-12">
      <div class="ibox float-e-margins">
          <div class="ibox-title">
              <h5>Lista de inventario para el producto {{producto}}</h5>
          </div>
            <div class="ibox-content">
                <table class="table table-bordered table-hover dataTables-example" >
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Cant. recibida</th>
                            <th>Fecha</th>
                            <th>Precio de compra</th>
                            <th>Botones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- cols 12 -->
</div>

{% endblock pagina %}


{% block extra_js %}
<script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'js/dataTables/datatables.min.js' %}"></script>
<script src="{% static 'js/dataTables/colvis.js' %}"></script>
<script type="text/javascript">
get_usuario_conectado();

var detalle_stock_modal = templater`
<div class="modal-content" id="contenido_modal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">Stock para ${'nombre'}</h4>
    </div>
    <div class="modal-body">
        <div class="col-sm-12">
            
        </div>            
    </div>
    <div class="modal-footer">
        <div class="col-sm-6">
            <a class="btn btn-info btn-md btn-block" data-dismiss="modal">Volver</a>
        </div>
        <div class="col-sm-6">
            <button type="submit" class="btn btn-success btn-md btn-block" id="guardar_cargo">Guardar</button>
        </div>
    </div>
</div>`;


var oTable;

function detalle_stock(id) {
    html = detalle_stock_modal({
        'nombre':'jovN'
    })
    $("#body_modal").empty()
    $("#body_modal").append(html);
    $("#modal_generico").modal('toggle');

}


function eliminar_dato(id) {
    swal({
        title: "Eliminar el inventario",
        text: '¿Deseas eliminar el inventario seleccionado?',
        type: "success",
        showCancelButton: true,
        confirmButtonColor: "red",
        confirmButtonText: "Eliminar",
        closeOnConfirm: false,
        html: true
    }, function () {

      $.ajax({
        type: "DELETE", //GET, POST, PUT, PATCH 
        url:   '/api/v1/stock/' + id + '/?borrar=si', 
        beforeSend: function (xhr) {   //Include the bearer token in header
          xhr.setRequestHeader("Authorization", 'JWT '+ HDD.get(settings.jwt_name));
        },
        complete: function (Req, textStatus)
        {
          if (Req.status === 204) 
          {
            swal({  
              title: "",
              text: "Se ha eliminado exitosamente.",
              type: "success",
              showCancelButton: false,
              confirmButtonColor: "#23c6c8",
              confirmButtonText: "Cerrar",
              closeOnConfirm: false
              }, function () {
                  //location.href = '/perfil/';
                  document.location='#/inventario/listar';
            });
          }               
        }// fin complete
      })

  });

}

$(document).ready(function () {
    $('#menu_inventario').addClass('active');
        refrescar_token();
    
        oTable = $('.table').dataTable({
        "aaSorting":[[0,"desc"]],
        "language": {
        "sLengthMenu":     "Mostrar _MENU_ inventarios",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando inventarios del _START_ al _END_ de un total de _TOTAL_ inventarios",
        "sInfoEmpty":      "Mostrando inventarios del 0 al 0 de un total de 0 inventarios",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ inventarios)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
          "sFirst":    "Primero",
          "sLast":     "Último",
          "sNext":     "Siguiente",
          "sPrevious": "Anterior"
        },

        "oAria": {
          "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      },
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "{% url 'inventario_app:listar_inventario_producto_ajax' id %}",
            "type": "POST", 
            "headers": { 'Authorization':  HDD.get(settings.jwt_name) },
        }
    });
});

$("#guardar_cargo").on('click',function(e){

    $.ajax({
      type: "POST", //GET, , PUT, PATCH 
      url:   '/api/v1/producto/', 
      beforeSend: function (xhr) {   //Include the bearer token in header
        xhr.setRequestHeader("Authorization", 'JWT '+ HDD.get(settings.jwt_name));
      },
      data:
      {
        nombre: $("#nombre_producto").val(),
        unidad:$("#unidad_producto").val()
      },
      complete: function (Req, textStatus)
      {
        if (Req.status === 201) 
        {
          swal({  
            title: "",
            text: "Se ha registrado el producto exitosamente.",
            type: "success",
            showCancelButton: false,
            confirmButtonColor: "#23c6c8",
            confirmButtonText: "Cerrar",
            closeOnConfirm: false
            }, function () {
                //location.href = '/perfil/';
                //oTable.api().ajax.reload(null, false);
                $("#nuevo_producto").modal('hide');
                swal.close();

          });
        }               
      }// fin complete
    })// fin ajax

});

</script>
{% endblock extra_js %}