simse/config/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve
from common.views import HomeView, View404, View500, ConfigDjangoJs

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="inicio"),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('config.apis_urls', namespace='api')),
    url(r'^', include('inventario.urls', namespace='inventario_app')),
    url(r'^', include('encargado.urls', namespace='encargados_app')),
    url(r'^', include('reporte.urls', namespace='reporte_app')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('notificaciones.urls', namespace='notificaciones_app')),    
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^(?!api|admin|\.).*$', HomeView.as_view(), name='home'),
    url(r'^config_django.js$', ConfigDjangoJs.as_view(content_type="application/javascript"), name="config_django"),

    
    #url(r'^template/skin-config.html/$', views.skin_config, name='skin_config'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = View404.as_view()
handler500 = View500.as_view()

if settings.DEBUG:

    urlpatterns += [
        url(r'^(?P<path>(favicon.ico))$', serve, {'document_root': settings.STATICFILES_DIRS[0]})
    ]

    import sys
    if "debug_toolbar" in sys.modules:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

simse/encargado/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from rest_framework.routers import SimpleRouter
from .viewsets import EncargadoViewSet, EncargadoActualizarPrecios, \
    EncargadoDetailViewSet, StocksEncargadoViewSet,\
    TransaccionesEncargadoViewSet, CuentaViewSet, MetodoPagoViewSet, \
    EncargadoVentaViewSet, TransaccionViewSet, BancoViewSet, \
    GananciaEncargadoViewSet, ClienteViewSet, EncargadoVentaPagarViewSet,\
    EncargadoVentaEliminarViewSet, EncargadoVentaReporteViewSet,\
    VentaViewSet, PagoVentaViewSet, CorregirPagosViewSet, EncargadoBuscarPrecios,\
    ActualizarGitViewSet


router = SimpleRouter()
router.register("cuenta", CuentaViewSet)
router.register("banco", BancoViewSet)
router.register("metodo_pago", MetodoPagoViewSet)
router.register("venta", VentaViewSet)
router.register("cliente", ClienteViewSet)
router.register("pago_venta", PagoVentaViewSet)


urlpatterns = [

    url(r'^encargado/(?P<pk>\d+)/$',
        EncargadoDetailViewSet.as_view(), name="encargado-detail"),

    url(r'^encargado/(?P<pk>\d+)/stocks/$',
        StocksEncargadoViewSet.as_view(), name="encargado-stocks"),

    url(r'^encargado/(?P<pk>\d+)/transacciones/$',
        TransaccionesEncargadoViewSet.as_view(), name="encargado-transacciones"),

    url(r'^encargado/(?P<pk>\d+)/ganancia/$',
        GananciaEncargadoViewSet.as_view(), name="encargado-ganancia"),

    url(r'^encargado/venta/$', EncargadoVentaViewSet.as_view(), name="encargado-venta"),
    url(r'^encargado/venta/pagar/$', EncargadoVentaPagarViewSet.as_view(), name="encargado-venta-pagar"),    
    url(r'^encargado/venta/eliminar/$', EncargadoVentaEliminarViewSet.as_view(), name="encargado-venta-eliminar"),    
    url(r'^encargado/venta/reporte$', EncargadoVentaReporteViewSet.as_view(), name="encargado-venta"),

    ### actualizar costos remotamente.
    url(r'^encargado/buscar_costos_web/$', EncargadoBuscarPrecios.as_view(), name="encargado-buscar_costos_web"),
    url(r'^encargado/actualizar_costos_web/$', EncargadoActualizarPrecios.as_view(), name="encargado-actualizar_costos_web"),
    ### actualizar costos remotamente.

    url(r'^encargado/corregir_pagos$', CorregirPagosViewSet.as_view(), name="corregir-pagos"),

    url(r'^encargado/$', EncargadoViewSet.as_view(), name="encargado"),

    url(r'^transaccion/$', TransaccionViewSet.as_view(), name="transaccion"),

    url(r'^actualizar_git/$',ActualizarGitViewSet.as_view(), name="actualizar_git"),
    
    # url(r'^cliente/$', ClienteViewSet.as_view(), name="cliente"),
    # url(r'^cliente/(?P<pk>\d+)$', ClienteViewSet.as_view(), name="cliente-detail"),

    url(r'^', include(router.urls)),



]

simse/encargado/urls.py
from django.conf.urls import include, url
from django.views.decorators.csrf import csrf_exempt
from common.decorators import Token
from .views import *
from .ajax import *

urlpatterns = [
    url(r'^encargados/$', Token(encargados), name="encargados"),
    url(r'^utilidades/$', Token(utilidades), name="utilidades"),
	url(r'^encargado/registrar$', Token(registrar), name="registrar_encargado"),
	url(r'^encargado/listar$', Token(listar), name="listar_encargado"),
	url(r'^encargado/modificar/(?P<pk>[0-9\.]+)$', Token(modificar), name="modificar_encargado"),
	url(r'^encargado/cuentas/(?P<pk>[0-9\.]+)$', Token(cuentas_encargado), name="encargados"),
    url(r'^encargado/ventas$', Token(ventas), name="ventas"),
    url(r'^encargado/ventas/reporte$', Token(encargado_ventas_reporte), name="encargado_ventas_reporte"),
    url(r'^encargado/ventas/reporte_metodo$', Token(encargado_metodo_reporte), name="encargado_metodo_reporte"),
    url(r'^encargado/ventas/listar$', Token(listar_ventas), name="listar_ventas"),
    url(r'^encargado/ventas/listar/(?P<pk>[0-9\.]+)$', Token(listar_ventas_encargado), name="listar_ventas_encargado"),
    url(r'^encargado/ventas/listar_cliente/(?P<pk>[0-9\.]+)$', Token(listar_ventas_cliente), name="listar_ventas_cliente"),
    url(r'^encargado/ventas/listar_cliente/iframe/(?P<pk>[0-9\.]+)$',
        Token(listar_ventas_cliente_iframe),
        name="listar_ventas_cliente_iframe"),
    url(r'^encargado/ventas/pagos$', Token(pagos), name="pagos"),
    url(r'^encargado/ventas/pagos/(?P<pk>[0-9\.]+)$', Token(pagos_venta), name="pagos"),
    url(r'^encargado/clientes/listar$', Token(listar_clientes), name="listar_clientes"),
    url(r'^encargado/clientes/listar/(?P<pk>[0-9\.]+)$', Token(listar_clientes_encargado), name="listar_clientes_encargado"),


    url(r'^inventario/encargado/listar$', Token(listar_inventario), name="listar_inventario_encargado"),


	url(r'^ajax/listar_encargado$', csrf_exempt(ListarEncargado.as_view()) , name="listar_encargado_ajax"),
	url(r'^ajax/listar_inventario_encargado$', csrf_exempt(ListarStockEncargado.as_view()), name="listar_inventario_encargado_ajax"),
    url(r'^ajax/listar_transacciones$', csrf_exempt(ListarTransacciones.as_view()), name="listar_transacciones_ajax"),
    url(r'^ajax/listar_transacciones_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarTransaccionesEncargado.as_view()), name="listar_transacciones_encargado_ajax"),
    
    url(r'^ajax/listar_ventas_reporte$', csrf_exempt(ListarVentasReporte.as_view()),
        name="listar_ventas_reporte_ajax"),
    url(r'^ajax/listar_ventas_reporte_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarVentasReporteEncargado.as_view()),
        name="listar_ventas_reporte_encargado_ajax"),
    
    url(r'^ajax/listar_ventas$', csrf_exempt(ListarVentas.as_view()), name="listar_ventas_ajax"),
    url(r'^ajax/listar_ventas_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarVentasEncargado.as_view()),
    	name="listar_ventas_encargado_ajax"),

    url(r'^ajax/listar_clientes$', csrf_exempt(ListarClientes.as_view()), name="listar_clientes_ajax"),
    url(r'^ajax/listar_clientes_encargado/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarClientesEncargado.as_view()),
        name="listar_clientes_encargado_ajax"),

    url(r'^ajax/listar_ventas_cliente/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarVentasCliente.as_view()),
        name="listar_ventas_cliente_ajax"),

    url(r'^ajax/listar_pagos_venta$', csrf_exempt(ListarPagos.as_view()), name="listar_pagos_ajax"),
    url(r'^ajax/listar_pagos_venta/(?P<pk>[0-9\.]+)/$', csrf_exempt(ListarPagosVenta.as_view()),
        name="listar_pagos_venta_ajax"),

    url(r'^ajax/listar_ventas_reporte_metodo/$', csrf_exempt(ListarVentasReporteMetodo.as_view()),
        name="listar_ventas_reporte_metodo_ajax"),
    url(r'^ajax/listar_ventas_reporte_encargado_metodo/(?P<pk>[0-9\.]+)/$',
        csrf_exempt(ListarVentasReporteMetodoEncargado.as_view()),
        name="listar_ventas_reporte_metodo_encargado_ajax"),
    

]

simse/inventario/urls.py
from django.conf.urls import include, url
from django.views.decorators.csrf import csrf_exempt
from common.decorators import Token
from .views import *
from .ajax import ListarStock, ListarStockProducto, ListarProductos,\
    ListarStockEncargado, ListarTraslados, ListarStockEncargadoAceptarNuevo,\
    ListarTrasladosSucursales

urlpatterns = [
	url(r'^inventario/registrar$', Token(registrar), name="registrar_inventario"),
	url(r'^inventario/listar$', Token(listar_inventario), name="listar_inventario"),
    url(r'^inventario/detalle/producto/(?P<pk>[0-9\.]+)/$', Token(detalle), name="registrar_inventario"),

	url(r'^ajax/listar_inventario$', csrf_exempt(ListarStock.as_view()), name="listar_inventario_ajax"),
    url(r'^ajax/listar_inventario_encargado$', csrf_exempt(ListarStockEncargado.as_view()),
        name="listar_inventario_encargado_ajax"),
    url(r'^ajax/listar_inventario_encargado_aceptar$', csrf_exempt(ListarStockEncargadoAceptarNuevo.as_view()),
        name="listar_inventario_encargado_aceptar_ajax"),

    url(r'^ajax/listar_traslados_sucursales$', csrf_exempt(ListarTrasladosSucursales.as_view()),
        name="listar_traslados_sucursales_ajax"),

    url(r'^ajax/listar_productos$', csrf_exempt(ListarProductos.as_view()), name="listar_productos_ajax"),
    url(r'^ajax/listar_traslados$', csrf_exempt(ListarTraslados.as_view()), name="listar_traslados_ajax"),    
    url(r'^ajax/listar_inventario/producto/(?P<pk>[0-9\.]+)/$',
        csrf_exempt(ListarStockProducto.as_view()) , name="listar_inventario_producto_ajax"),

]

simse/encargado/views.py
from django.shortcuts import render
from django.http import JsonResponse

from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from .models import Encargado, Cuenta, TransaccionHistory, Venta, CierreEncargado
from common.utils import permission


def listar(request):
    return render(request,'listar_encargado.html',{})


def listar_ventas(request):
    return render(request,'listar_ventas.html',{
    	'params':request.GET,
        'template':"base_ajax.html"
    })


def listar_ventas_encargado(request, pk):
    return render(request,'listar_ventas.html',{
    	'pk_de_encargado':pk,
        'template':"base_ajax.html"
    })


def listar_ventas_cliente(request, pk):
    return render(request,'listar_ventas.html',{
    	'pk_de_cliente':pk,
        'params':request.GET,
        'template':"base_ajax.html"
    })

def listar_ventas_cliente_iframe(request, pk):
    return render(request,'listar_ventas.html',{
        'pk_de_cliente':pk,
        'params':request.GET,
        'template':"base_simple.html"
    })



def registrar(request):
    return render(request,'registrar_encargado.html',{})
registrar.permisos = ["encargado:add_encargado",]


def modificar(request,pk):
	context = {
		'encargado_id' : pk,
		'persona_id': Encargado.objects.get(id=pk).persona.id
	}
	return render(request,'modificar_encargado.html',context)    


def utilidades(request):
    return render(request,'utilidades.html',{})	


def encargados(request):
    return render(request,'encargados.html',{}) 


def ventas(request):
    return render(request,'ventas.html',{}) 


def pagos(request):
    return render(request,'pagos.html',{}) 


def pagos_venta(request, pk):
    venta = Venta.objects.get(pk=pk)
    return render(request,'pagos.html',{
        'pk_de_venta':pk,
        'deuda':venta.restante
    })


def listar_clientes(request):
    return render(request,'listar_clientes.html',{}) 


def listar_clientes_encargado(request, pk):
    return render(request,'listar_clientes.html',{
    	'pk_de_encargado':pk
    })


def cuentas_encargado(request,pk):

	encargado = Encargado.objects.get(id=pk)
	cuenta = Cuenta.objects.get(persona=encargado.persona)
	operaciones = TransaccionHistory.objects.filter(
		Q(origen=cuenta) | Q(destino=cuenta)
		).filter(generado=False)
    
	context = {
		'encargado_id' : pk,
		'nombre': encargado.persona.name(),
		'persona_id': encargado.persona.id,
		'cuenta_id': cuenta.id,
		'saldo': cuenta.monto.monto,
		'simbolo': 'Bss',
		'operaciones':operaciones.count()
	}	
	return render(request,'cuentas_encargado.html',context)	
    

def listar_inventario(request):
    return render(request,'listar_inventario_encargado.html',{})


def encargado_ventas_reporte(request):
    params = request.GET
    try:
        enc = request.user.persona_set.encargado_set
        ultimo_cierre = CierreEncargado.objects.filter(condicion=True,
                        encargado=enc).latest()
    except Exception as e:
        ultimo_cierre = None
    
    return render(request,'encargado_ventas_reporte.html',{
    	'params':params,
        'ultimo_cierre':ultimo_cierre
    }) 
    

def encargado_metodo_reporte(request):
    params = request.GET
    return render(request,'encargado_metodo_pago_reporte.html',{
        'params':params,
    }) 

simse/encargado/templates/cuentas_encargado.html
{% extends "base_ajax.html" %}
{% load static %}
{% block titulo %}Cuenta Encargado{% endblock titulo %}

{% block head %}
    <style>
        .mb{
            margin-top: 10px;
            margin-bottom: -5px;
        }
        .thumb {
            height: 400px;
            border: 1px solid #000;
            margin: 10px 5px 0 0;
        }       
    </style>
{% endblock head %}

{% block pagina %}
    <div class="row">

        <div class="col-md-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Balance del encargado #{{encargado_id}} {{nombre}}: </h5>
            </div>
            <div class="ibox-content">

                <div class="row">
                    <div class="col-lg-3">
                        <div class="widget style1 lazur-bg">
                            <div class="row vertical-align">
                                <div class="col-xs-9 text-right">
                                    <h2 class="font-bold"> {{simbolo}} {{ saldo|floatformat:"2" }}</h2>
                                </div>
                            </div>
                        </div>
                    </div>       

                    <div class="col-lg-6">
                        <div class="widget style1 yellow-bg">
                            <div class="row vertical-align">
                                <div class="col-xs-9 text-right">
                                    <h2 class="font-bold"> {{operaciones}} Operaciones</h2>
                                </div>
                            </div>
                        </div>
                    </div> 


                </div>              
             
            </div>
        </div>
        </div> <!-- cols 12 -->

        <div class="col-md-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Cuenta</h5>
            </div>
            <div class="ibox-content">
            <ul class="nav nav-tabs">
               <li class="active"><a data-toggle="tab" href="#tab-1">Transferencia</a></li>
               <li class=""><a data-toggle="tab" id="atajo" href="#tab-2">Movimientos</a></li>
            </ul>
               <div class="tab-content">

                  <div id="tab-1" class="tab-pane active">
                      <div class="panel-body">
                        <form method="post" id="form_cuenta">{% csrf_token %}
                        <div class="form-group row" autocomplete="off">
                            <div class="col-sm-6 espacio">
                                <input type="text" class="form-control" name="monto" id="monto" placeholder="monto" onkeypress="return permite(event, 'num')"/>
                            </div>
                            <div class="col-sm-6">
                                <select class="form-control" id="tipo_movimiento">
                                    <option value="+"> Abono </option>
                                    <option value="-"> Retiro </option>
                                </select>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" autocomplete="off">
                                    <textarea class="form-control" rows="1" id='descripcion' style="width: 100%; color: #000;" placeholder="Coloque una descripcion"></textarea>
                                </div>                        
                            </div>    
                        </div>

                        <div class="form-group row">
                          <div class="col-md-2 col-md-offset-1"><a class="btn btn-primary" href="#/encargado/listar">Volver</a></div>
                          <div class="col-md-2 col-md-offset-7">
                            <button type="submit" class="btn btn-primary" name="guardar_encargado">Guardar</button>
                          </div>
                        </div>
                    </form>

                      </div>
                  </div>
                  <div id="tab-2" class="tab-pane">
                      <div class="panel-body">
                        <div class="col">
                            <table id="movimientos" class="table  table-bordered table-hover" width="100%">
                                <thead>
                                    <tr>
                                        <th>Fecha</th>
                                        <th>Tipo Operacion</th>
                                        <th>Monto</th>
                                        <th>Descripcion</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr></tr>
                                </tbody>
                            </table>
                            
                        </div>
                      </div>
                  </div>
              </div>
            </div>
        </div>
        </div> <!-- cols 12 -->
    </div>
{% endblock pagina %}

{% block extra_js %}
<script src="{% static 'js/dataTables/datatables.min.js' %}"></script>
<script src="{% static 'js/dataTables/colvis.js' %}"></script>
<script src="{% static 'js/validaciones.js' %}"></script>
<script type="text/javascript">
get_usuario_conectado();
HDD.set('last_url',window.location.pathname);
var url_movimientos = "{% url 'encargados_app:listar_transacciones_encargado_ajax' encargado_id %}"
$(document).ready(function () 
{
    $("#menu_encargado").addClass("active");
    $('#form_cuenta').validate({
    errorPlacement: function (error, element)
    {
        element.before(error);
    },
    rules: {
        monto: {
            required: true,
        }
    },
    messages: {
        monto: {
            required: "Campo obligatorio"
        }
    },
    submitHandler: function (_form)
    {
        if ($("#tipo_movimiento").val() == '+' )
        {
            monto = parseFloat($("#monto").val())
        }
        else
        {
            monto = parseFloat($("#monto").val()) * (-1);
        }


        $.ajax({
            type: "POST", //GET, POST, PUT, PATCH 
            url:   '/api/v1/transaccion/',
            beforeSend: function (xhr) {   //Include the bearer token in header
              xhr.setRequestHeader("Authorization", 'JWT '+ HDD.get(settings.jwt_name));
            },                
            data:{
                cuenta_destino: "{{cuenta_id}}",
                monto: monto,
                descripcion: $("#descripcion").val()
            },
            complete: function (Req, textStatus)
            {
                var res = JSON.parse(Req.responseText)

                if (Req.status === 400) 
                {
                    /* Campos a obtener mensajes */
                    campos = ['cuenta_destino','monto_transaccion']
                    errores = get_error_api(res,campos);
                    // devuelvo los mensajes y los muestro en swalert
                    _error(errores);

                }
                if (Req.status === 201) 
                {
                    swal({  
                        title: "",
                        text: "Operacion realizada exitosamente",
                        type: "success",
                        showCancelButton: false,
                        confirmButtonColor: "#23c6c8",
                        confirmButtonText: "Cerrar",
                        closeOnConfirm: false
                        }, function () {
                            location.href = '/encargado/cuentas/'+ "{{encargado_id}}";
                    });
                }
            }//fin complete
        });
        return false;
      }
    //...
});

    oTable = $('#movimientos').dataTable({
    "aaSorting":[[0,"desc"]],
    "language": {
    "sLengthMenu":     "Mostrar _MENU_ inventarios",
    "sZeroRecords":    "No se encontraron resultados",
    "sEmptyTable":     "Ningún dato disponible en esta tabla",
    "sInfo":           "Mostrando inventarios del _START_ al _END_ de un total de _TOTAL_ inventarios",
    "sInfoEmpty":      "Mostrando inventarios del 0 al 0 de un total de 0 inventarios",
    "sInfoFiltered":   "(filtrado de un total de _MAX_ inventarios)",
    "sInfoPostFix":    "",
    "sSearch":         "Buscar:",
    "sThousands": ".",
    "sDecimal": ".",
    "sUrl":            "",
    "sInfoThousands":  ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
      "sFirst":    "Primero",
      "sLast":     "Último",
      "sNext":     "Siguiente",
      "sPrevious": "Anterior"
    },

    "oAria": {
      "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
      "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    }
  },
    "processing": true,
    "serverSide": true,
    "ajax": {
        "url": url_movimientos,
        "type": "POST",
        "headers": { 'Authorization':  HDD.get(settings.jwt_name) }
    },

});

}); // Fin de ready

</script>
{% endblock extra_js %}

simse/encargado/templates/listar_inventario_encargado.html
{% extends "base_ajax.html" %}
{% load static %}
{% block titulo %} Lista de Inventarios {% endblock titulo %}

 

{% block breadcrumb %}
fdf
{% endblock %}

{% block pagina %}
  <div class="row">
      <div class="col-md-12">
      <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Lista de inventario</h5>
            </div>
            <div class="ibox-content">
                <div class="tabs-container">
                  <ul class="nav nav-tabs">
                      <li class="active"><a data-toggle="tab" href="#tab-1">Inventario</a></li>
                      <li class=""><a data-toggle="tab" href="#tab-2">otra</a></li>
                  </ul>
                </div>
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            <table id="stocks" class="table table-bordered table-hover dataTables-example" >
                                <thead>
                                    <tr>
                                        <th>Producto</th>
                                        <th>Cant. recibida</th>
                                        <th>Monto</th>
                                        <th>Botones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div id="tab-2" class="tab-pane">
                        <div class="panel-body">
                            <a type="button" class="btn btn-success" onclick="nuevo_producto_action()"><i class="fa fa-pencil"></i></a>
                            <table id="productos" class="table table-bordered table-hover dataTables-example" >
                                <thead>
                                    <tr>
                                        <th>Producto</th>
                                        <th>Botones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>                    
                </div>
                
            </div>
        </div>
    </div> <!-- cols 12 -->
</div>


<div class="modal fade bs-example-modal-lg" id="modal_generico" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document" id="body_modal">
        
    </div>
</div>

{% endblock pagina %}


{% block extra_js %}
<script src="{% static 'js/dataTables/colvis.js' %}"></script>
<script type="text/javascript">
get_usuario_conectado();

var oTable;
var oTable2;

function detalle_stock(id) {
    html = detalle_stock_modal({
        'nombre':'jovN'
    })
    $("#body_modal").empty()
    $("#body_modal").append(html);
    $("#modal_generico").modal('toggle');
}



$(document).ready(function () {
    $('#menu_inventario').addClass('active');
    refrescar_token();

    oTable = $('#stocks').dataTable({
        "aaSorting":[[0,"desc"]],
        "language": {
        "sLengthMenu":     "Mostrar _MENU_ inventarios",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando inventarios del _START_ al _END_ de un total de _TOTAL_ inventarios",
        "sInfoEmpty":      "Mostrando inventarios del 0 al 0 de un total de 0 inventarios",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ inventarios)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
          "sFirst":    "Primero",
          "sLast":     "Último",
          "sNext":     "Siguiente",
          "sPrevious": "Anterior"
        },

        "oAria": {
          "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      },
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "{% url 'encargados_app:listar_inventario_encargado_ajax' %}",
            "type": "POST",
            "headers": { 'Authorization':  HDD.get(settings.jwt_name) },
        }
    });


    oTable2 = $('#productos').dataTable({
        "aaSorting":[[0,"desc"]],
        "language": {
        "sLengthMenu":     "Mostrar _MENU_ inventarios",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando inventarios del _START_ al _END_ de un total de _TOTAL_ inventarios",
        "sInfoEmpty":      "Mostrando inventarios del 0 al 0 de un total de 0 inventarios",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ inventarios)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
          "sFirst":    "Primero",
          "sLast":     "Último",
          "sNext":     "Siguiente",
          "sPrevious": "Anterior"
        },

        "oAria": {
          "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      },
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "{% url 'inventario_app:listar_productos_ajax' %}",
            "type": "POST",
            "headers": { 'Authorization':  HDD.get(settings.jwt_name) },
        }
    });

});

</script>
{% endblock extra_js %}